visited_stations = [
    'Várzea Paulista',
    'Francisco Morato',
    'Baltazar Fidélis',
    'Caieiras',
    'Vila Clarice',
    'Piqueri',
    'Palmeiras - Barra Funda',
    'Luz',
    'Brás',
    'Santana',
    'Portuguesa-tietê',
    'São Bento',
    'Sé',
    'Vergueiro',
    'Paraíso',
    'Ana Rosa',
    'Vila Mariana',
    'Santa Cruz',
    'Praça Da Árvore',
    'São Judas',
    'Conceição',
    'Jabaquara',
    'Marechal Deodoro',
    'Santa Cecília',
    'República',
    'Anhangabaú',
    'Pedro II',
    'Tatuapé',
    'Carrão',
    'Patriarca',
    'Artur Alvim',
    'Corinthians-itaquera',
    'Mogi Das Cruzes',
    'Estudantes',
    'Aeroporto Guarulhos',
    'São Lucas',
    'Sacomã',
    'Santos-imigrantes',
    'Brigadeiro',
    'Trianon-masp',
    'Consolação',
    'S. N. Sra. De Fátima-sumaré',
    'Vila Madalena',
    'Jardim Belval',
    'Osasco',
    'Presidente Altino',
    'São Paulo - Morumbi',
    'Butantã',
    'Faria Lima',
    'Fradique Coutinho',
    'Oscar Freire',
    'Paulista',
    'Higienópolis-mackenzie',
    'Aacd - Servidor',
    'Eucaliptos',
    'Brooklin',
    'Borba Gato',
    'Alto Da Boa Vista',
    'Giovanni Gronchi',
    'Campo Limpo'
]